### ISSUE TITLE
Is https://dummy.github.io/ the result page? If yes, it is broken

### ISSUE THREAD

**Issue by richelbilderbeek** [ar2pi/sample-mkdocs-gh-project#1]
Don't we all like it when someone notifies us of our broken links :-)

Cheers, Richel

**Comment by ar2pi** [comment]
Very true.
This boilerplate repo doesn't make much sense without proper setup. Updated Readme accordingly in https://github.com/ar2pi/sample-mkdocs-gh-project/commit/f56b15436364f9a06db0f59d7492fbd078c5e639
Many thanks! 

Side note, this is the first issue I've ever seen open on one of my public repos, much humbled and grateful x)

**Comment by ar2pi** [comment]
Closing and considering as completed as no update in past two weeks.

**Comment by richelbilderbeek** [comment]
Thanks @ar2pi, thanks for accepting my suggestion, I appreciate that! Enjoy getting your first GitHub Issue compliment and keep up the good job :-)
